In [26]:
## INSTALL PYTHON LIBRARIES INTO OUR NOTEBOOK
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install scipy
!pip install statsmodels

Requirement already satisfied: pandas in c:\users\gifton\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\gifton\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gifton\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gifton\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gifton\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\gifton\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in c:\users\gifton\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\users\gifton\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\gifton\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in c:\users\gifton\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\gifton\anaconda3\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\gifton\anaconda3\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\gifton\anaconda3\lib\site-packages (from seaborn) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\gifton\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gifton\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gifton\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\gifton\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: scipy in c:\users\gifton\anaconda3\lib\site-packages (1.16.3)
Requirement already satisfied: numpy<2.6,>=1.25.2 in c:\users\gifton\anaconda3\lib\site-packages (from scipy) (2.3.5)
Requirement already satisfied: statsmodels in c:\users\gifton\anaconda3\lib\site-packages (0.14.5)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\gifton\anaconda3\lib\site-packages (from statsmodels) (2.3.5)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\gifton\anaconda3\lib\site-packages (from statsmodels) (1.16.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\gifton\anaconda3\lib\site-packages (from statsmodels) (2.3.3)
Requirement already satisfied: patsy>=0.5.6 in c:\users\gifton\anaconda3\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\users\gifton\anaconda3\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gifton\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gifton\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gifton\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\gifton\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

## Import All the Libraries into our Jupyter Notebook environment

In [1]:
## IMPORT THE LIBRARIES ONTO THE NOTEBOOK
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import statsmodels.api as sm

In [2]:
## We want to display all columns in the data
df = pd.set_option('display.max_columns', None)

In [3]:
## Load and Read our data into the Notebook
## We shall be using Individual World Billionaires datsets
df_1 = pd.read_csv(r"C:\Users\Gifton\Videos\0.0002 DATA ANALYTICS\2026, APRIL PROJECTS\102 PROJECT\billionaire_individual_2026.csv") #For INDIVIDUAL BILLIONAIRES

## PART A: Individual Billionaires Data Analytics
- We start our project analysis first by using the Individual Billionaires data

In [4]:
df_1.head(5) ## To diplay the top 5 rows

,rank,person_name,gender,age,country,iso3,wb_country_name,state,city,net_worth_usd_m,net_worth_usd,source_of_wealth,industries,primary_industry,self_made,wealth_gdp_ratio_pct,wealth_per_citizen_usd,wealth_country_share_pct,sector_dominance_score,gdp_usd,population,gdp_year,forbes_uri,scrape_timestamp,birth_year
0,1,Elon Musk,M,54.0,United States,USA,United States,Texas,Austin,800629.06,8.006291e+11,"Tesla, SpaceX",Technology,Technology,True,2.784704,2354.0229,9.5966,23.35,2.875096e+13,340110988.0,2024.0,elon-musk,2026-04-10 21:32 UTC,1971.0
1,2,Larry Page,M,53.0,United States,USA,United States,California,Palo Alto,260898.20,2.608982e+11,Google,Technology,Technology,True,0.907442,767.0972,3.1272,23.35,2.875096e+13,340110988.0,2024.0,larry-page,2026-04-10 21:32 UTC,1973.0
2,3,Jeff Bezos,M,62.0,United States,USA,United States,Florida,Miami,248778.91,2.487789e+11,Amazon,Technology,Technology,True,0.865289,731.4639,2.9819,23.35,2.875096e+13,340110988.0,2024.0,jeff-bezos,2026-04-10 21:32 UTC,1964.0
3,4,Sergey Brin,M,52.0,United States,USA,United States,California,Los Altos,240743.24,2.407432e+11,Google,Technology,Technology,True,0.837340,707.8373,2.8856,23.35,2.875096e+13,340110988.0,2024.0,sergey-brin,2026-04-10 21:32 UTC,1973.0
4,5,Mark Zuckerberg,M,41.0,United States,USA,United States,California,Palo Alto,216089.31,2.160893e+11,Facebook,Technology,Technology,True,0.751590,635.3494,2.5901,23.35,2.875096e+13,340110988.0,2024.0,mark-zuckerberg,2026-04-10 21:32 UTC,1984.0

In [5]:
df_1.tail(5) ## To display the bottom 5 rows

,rank,person_name,gender,age,country,iso3,wb_country_name,state,city,net_worth_usd_m,net_worth_usd,source_of_wealth,industries,primary_industry,self_made,wealth_gdp_ratio_pct,wealth_per_citizen_usd,wealth_country_share_pct,sector_dominance_score,gdp_usd,population,gdp_year,forbes_uri,scrape_timestamp,birth_year
3379,3380,Shintaro Tsuji,M,98.0,Japan,JPN,Japan,NaN,Tokyo,292.73,292727000.0,Hello Kitty,Fashion & Retail,Fashion & Retail,True,0.007268,2.3612,0.134,25.83,4.027598e+12,123975371.0,2024.0,shintaro-tsuji,2026-04-10 21:32 UTC,1928.0
3380,3381,Elizabeth Holmes,F,42.0,United States,USA,United States,California,NaN,0.00,0.0,blood testing,Healthcare,Healthcare,True,NaN,NaN,0.000,23.35,2.875096e+13,340110988.0,2024.0,elizabeth-holmes,2026-04-10 21:32 UTC,1984.0
3381,3381,Gary Wang,M,32.0,United States,USA,United States,NaN,Nassau,0.00,0.0,cryptocurrency exchange,Finance & Investments,Finance & Investments,True,NaN,NaN,0.000,23.35,2.875096e+13,340110988.0,2024.0,gary-wang-1,2026-04-10 21:32 UTC,1993.0
3382,3381,Rene Benko,M,49.0,Austria,AUT,Austria,NaN,NaN,0.00,0.0,"Real estate, retail",Real Estate,Real Estate,True,NaN,NaN,0.000,37.00,5.347907e+11,9177982.0,2024.0,rene-benko,2026-04-10 21:32 UTC,1977.0
3383,3381,Sam Bankman-Fried,M,34.0,United States,USA,United States,NaN,Nassau,0.00,0.0,cryptocurrency exchange,Finance & Investments,Finance & Investments,True,NaN,NaN,0.000,23.35,2.875096e+13,340110988.0,2024.0,sam-bankman-fried,2026-04-10 21:32 UTC,1992.0

In [ ]:
## lets conduct a comprehensive check to gather more information about our data
def data_quality_check(df_1):
    info_report = {
        'shape': df_1.shape,
        'total_records': len(df_1),
        'missing_records': df_1.isnull().sum(),
        'duplicate_rows': df_1.duplicated().sum(),
    }
    return info_report

info_report = data_quality_check(df_1)
print(info_report)
    ## RESULTS: Data has 3384 rows and 25 columns, Total records are 3384, There are NO Duplicate rows. However there are NULLS in some rows in respect to the column names displayed.

## Dealing with Nulls
- We can use the fillna() method to replace Nulls with some values. Case examples use either average records for Numeric Data, while Non Numeric data can be filled with 'Unknown'. This is important to ensure data analysis findings try reflect data

In [7]:
def description_of_null_columns(df_1):
    desc_report = {
        'avg_age': df_1['age'].mean(),
        'avg_birth_year': df_1['birth_year'].mean(),
        'avg_wealth_gdp': df_1['wealth_gdp_ratio_pct'].mean(),
        'avg_wealt_citizen': df_1['wealth_per_citizen_usd'].mean(),
}
    return desc_report
desc_report = description_of_null_columns(df_1)
print(desc_report)

## The line of code is used to obtain Avg Values for the Numeric columns which then can be filled to records with Nulls

{'avg_age': np.float64(65.2880695443645), 'avg_birth_year': np.float64(1960.1321942446043), 'avg_wealth_gdp': np.float64(0.8132835606508876), 'avg_wealt_citizen': np.float64(297.56616446745556)}

In [ ]:
def filled_null_records(df_1):
    fill_nulls = {
       'age': df_1['age'].fillna(65.0, inplace=True),
        'birth_year' : df_1['birth_year'].fillna(1960.0, inplace=True),
        'wealth_per_citizen_usd' : df_1['wealth_per_citizen_usd'].fillna(297.6, inplace=True),
        'wealth_gdp_ratio_pct' : df_1['wealth_gdp_ratio_pct'].fillna(0.8, inplace=True),
}
    return fill_nulls
fill_nulls = filled_null_records(df_1)
print(fill_nulls)

In [9]:
df_1.isnull().sum()

rank                           0
person_name                    0
gender                         0
age                            0
country                        0
iso3                           0
wb_country_name                0
state                       1842
city                          49
net_worth_usd_m                0
net_worth_usd                  0
source_of_wealth               0
industries                     0
primary_industry               0
self_made                      0
wealth_gdp_ratio_pct           0
wealth_per_citizen_usd         0
wealth_country_share_pct       0
sector_dominance_score         0
gdp_usd                        0
population                     0
gdp_year                       0
forbes_uri                     0
scrape_timestamp               0
birth_year                     0
dtype: int64

In [ ]:
## Fill the NULLS For the Non Numeric data columns [State and city] with ['Unknown']
def fill_nulls(df_1):
    filled_null_cols = {
    'state':df_1['state'].fillna('Unknown', inplace=True),
    'city':df_1['city'].fillna('Unknown', inplace=True),
    }
    return filled_null_cols
filled_null_cols = fill_nulls(df_1)
print(filled_null_cols)

In [11]:
## Let us confirm using isnull() if all the Nulls have been dealth with:
df_1.isnull().sum()
    ## Having dealt with Data Cleaning protocol for the data, we can proceed to conduct Exploratory Analysis

rank                        0
person_name                 0
gender                      0
age                         0
country                     0
iso3                        0
wb_country_name             0
state                       0
city                        0
net_worth_usd_m             0
net_worth_usd               0
source_of_wealth            0
industries                  0
primary_industry            0
self_made                   0
wealth_gdp_ratio_pct        0
wealth_per_citizen_usd      0
wealth_country_share_pct    0
sector_dominance_score      0
gdp_usd                     0
population                  0
gdp_year                    0
forbes_uri                  0
scrape_timestamp            0
birth_year                  0
dtype: int64

## PART B: Explortory Data Analysis
- This phase is where we explore our data using EDA Techniques to learn more about it, gain insights and answer some business questions.

### Q1. For each primary industry, what is the Total and Average Networth in USD Billions among the billionaires? How many billionares belong to each industry? Which are the top 10 primary industry with the highest total net worth?

In [ ]:
## Obtain net_worth in USD Billions
df_1['net_worth_usd_b'] = df_1['net_worth_usd_m']/1000
print(df_1['net_worth_usd_b'])

In [ ]:
## Define more data metrics so as to allow grouping by the Primary Industry
billionaire_analysis = df_1.groupby('primary_industry').agg(
    billionaire_count = ('person_name', 'count'),
    total_net_worth = ('net_worth_usd_b', 'sum'),
    avg_net_worth = ('net_worth_usd_b', 'mean'),
    max_net_worth =('net_worth_usd_b', 'max'),
    min_net_worth =('net_worth_usd_b', 'min')).reset_index()

billionaire_analysis.head(10)

In [ ]:
## The Top 10 Primary Industry with Highest Total networth?
top_10_industry = billionaire_analysis.nlargest(10, 'total_net_worth')
top_10_industry

### Q2. How does the Average Wealth GDP Ratio percentage differ when grouping by gender and self made status across countries?

In [16]:
## We define a data frame ['gdp_stats']
gdp_stats = df_1.groupby(['country', 'gender', 'self_made'])['wealth_gdp_ratio_pct'].mean().reset_index()
gdp_stats

           country gender  self_made  wealth_gdp_ratio_pct
0      Afghanistan      M       True              9.592226
1          Albania      M       True              6.881108
2          Algeria      M       True              1.348607
3        Argentina      M      False              0.837790
4        Argentina      M       True              0.559036
..             ...    ...        ...                   ...
181  United States      M       True              0.034039
182      Venezuela      M       True              9.371313
183        Vietnam      F       True              0.597821
184        Vietnam      M       True              1.385099
185       Zimbabwe      M       True              5.245250

[186 rows x 4 columns]

In [17]:
## To obtain a more comprehensive report on the differenceon wealth_gdp_ratio_pct:
gdp_stats = df_1.groupby(['country', 'gender', 'self_made']).agg(
    avg_wealth_gdp_ratio = ('wealth_gdp_ratio_pct','mean')).reset_index()

gdp_stats

           country gender  self_made  avg_wealth_gdp_ratio
0      Afghanistan      M       True              9.592226
1          Albania      M       True              6.881108
2          Algeria      M       True              1.348607
3        Argentina      M      False              0.837790
4        Argentina      M       True              0.559036
..             ...    ...        ...                   ...
181  United States      M       True              0.034039
182      Venezuela      M       True              9.371313
183        Vietnam      F       True              0.597821
184        Vietnam      M       True              1.385099
185       Zimbabwe      M       True              5.245250

[186 rows x 4 columns]

### Q3. Which are the 10 countries have the highest sum of net_worth_usd_m

In [18]:
countries_total = df_1.groupby('country')['net_worth_usd_m'].sum().reset_index()
countries_total

           country  net_worth_usd_m
0      Afghanistan          1399.31
1          Albania          1861.09
2          Algeria          3632.10
3        Argentina         19622.93
4          Armenia          1252.37
..             ...              ...
75  United Kingdom        270350.57
76   United States       8342857.33
77       Venezuela         11227.11
78         Vietnam         41536.08
79        Zimbabwe          2178.85

[80 rows x 2 columns]

In [19]:
## Obtain the top 10 countries with the highest Total Networth in USD M
top10_countries = countries_total.nlargest(10, 'net_worth_usd_m')
top10_countries

          country  net_worth_usd_m
76  United States       8342857.33
14          China       2134679.32
32          India        989622.96
26        Germany        985821.88
59         Russia        653326.62
24         France        591640.15
36          Italy        463424.60
12         Canada        443797.17
29      Hong Kong        422587.23
68    Switzerland        273626.95

### Q4. Create an age bracket for the billionaires and group the billionaires count according  to their respective age brackets and split by gender

In [20]:
## Lets first inspect for the Maximum and Minimum Billionaire Ages
df_1['age'].max()
    # Maximum billionaire age is 104 years

104.0

In [21]:
df_1['age'].min()
    # The Minimum billionaire age is 20 years

20.0

In [22]:
## lets group the Billionaires into resoective age bracket
    #20-35 Years = Young enterpreneurs
    #36-55 Years = Established professionals
    #56-70 Years = Senior Wealth holders
    # 71+ Years = Old billionaires

## Define a function for Age Brackets
def age_bracket(age):
    if 20 <= age <= 35:
        return 'Young entrepreneurs'
    elif 36 <= age <= 55:
        return 'Established professionals'
    elif 56 <= age <= 70:
        return 'Senior Wealth holders'
    elif age >= 71:
        return 'Old billionaires'

df_1['age_bracket'] = df_1['age'].apply(age_bracket)

In [23]:
## To view the Top 10 Rows
df_1.head(10)

,rank,person_name,gender,age,country,iso3,wb_country_name,state,city,net_worth_usd_m,net_worth_usd,source_of_wealth,industries,primary_industry,self_made,wealth_gdp_ratio_pct,wealth_per_citizen_usd,wealth_country_share_pct,sector_dominance_score,gdp_usd,population,gdp_year,forbes_uri,scrape_timestamp,birth_year,net_worth_usd_b,age_bracket
0,1,Elon Musk,M,54.0,United States,USA,United States,Texas,Austin,800629.06,8.006291e+11,"Tesla, SpaceX",Technology,Technology,True,2.784704,2354.0229,9.5966,23.35,2.875096e+13,340110988.0,2024.0,elon-musk,2026-04-10 21:32 UTC,1971.0,800.62906,Established professionals
1,2,Larry Page,M,53.0,United States,USA,United States,California,Palo Alto,260898.20,2.608982e+11,Google,Technology,Technology,True,0.907442,767.0972,3.1272,23.35,2.875096e+13,340110988.0,2024.0,larry-page,2026-04-10 21:32 UTC,1973.0,260.89820,Established professionals
2,3,Jeff Bezos,M,62.0,United States,USA,United States,Florida,Miami,248778.91,2.487789e+11,Amazon,Technology,Technology,True,0.865289,731.4639,2.9819,23.35,2.875096e+13,340110988.0,2024.0,jeff-bezos,2026-04-10 21:32 UTC,1964.0,248.77891,Senior Wealth holders
3,4,Sergey Brin,M,52.0,United States,USA,United States,California,Los Altos,240743.24,2.407432e+11,Google,Technology,Technology,True,0.837340,707.8373,2.8856,23.35,2.875096e+13,340110988.0,2024.0,sergey-brin,2026-04-10 21:32 UTC,1973.0,240.74324,Established professionals
4,5,Mark Zuckerberg,M,41.0,United States,USA,United States,California,Palo Alto,216089.31,2.160893e+11,Facebook,Technology,Technology,True,0.751590,635.3494,2.5901,23.35,2.875096e+13,340110988.0,2024.0,mark-zuckerberg,2026-04-10 21:32 UTC,1984.0,216.08931,Established professionals
5,6,Larry Ellison,M,81.0,United States,USA,United States,Florida,Manalapan,179055.65,1.790556e+11,Oracle,Technology,Technology,True,0.622782,526.4624,2.1462,23.35,2.875096e+13,340110988.0,2024.0,larry-ellison,2026-04-10 21:32 UTC,1944.0,179.05565,Old billionaires
6,7,Jensen Huang,M,63.0,United States,USA,United States,California,Los Altos,163293.01,1.632930e+11,Semiconductors,Technology,Technology,True,0.567957,480.1168,1.9573,23.35,2.875096e+13,340110988.0,2024.0,jensen-huang,2026-04-10 21:32 UTC,1963.0,163.29301,Senior Wealth holders
7,8,Michael Dell,M,61.0,United States,USA,United States,Texas,Austin,158994.27,1.589943e+11,Dell Technologies,Technology,Technology,True,0.553005,467.4776,1.9058,23.35,2.875096e+13,340110988.0,2024.0,michael-dell,2026-04-10 21:32 UTC,1965.0,158.99427,Senior Wealth holders
8,9,Bernard Arnault & family,M,77.0,France,FRA,France,Unknown,Paris,151350.62,1.513506e+11,LVMH,Fashion & Retail,Fashion & Retail,False,4.788906,2207.8332,25.5815,39.58,3.160443e+12,68551653.0,2024.0,bernard-arnault,2026-04-10 21:32 UTC,1949.0,151.35062,Old billionaires
9,10,Rob Walton & family,M,81.0,United States,USA,United States,Arkansas,Bentonville,144971.96,1.449720e+11,Walmart,Fashion & Retail,Fashion & Retail,False,0.504234,426.2490,1.7377,23.35,2.875096e+13,340110988.0,2024.0,rob-walton,2026-04-10 21:32 UTC,1944.0,144.97196,Old billionaires

In [24]:
## We can then group the bilionaires by age age bracket split by gender. 
billionaire_stats = df_1.groupby(['age_bracket', 'gender']).agg(
    billionaire_count = ('person_name', 'count'),
    total_net_worth_m = ('net_worth_usd_m', 'sum')).reset_index()
billionaire_stats

                 age_bracket gender  billionaire_count  total_net_worth_m
0  Established professionals      F                114          363054.79
1  Established professionals      M                568         3933949.92
2           Old billionaires      F                151         1217788.48
3           Old billionaires      M               1078         6787399.62
4      Senior Wealth holders      F                193          926668.53
5      Senior Wealth holders      M               1199         6114912.82
6        Young entrepreneurs      F                 16           37886.65
7        Young entrepreneurs      M                 65          257888.89

In [25]:
## To view age bracket with the most total_net_worth_m, we order in descENDING ORDER
billionaire_stats_order = billionaire_stats.sort_values('total_net_worth_m', ascending=False)
billionaire_stats_order

                 age_bracket gender  billionaire_count  total_net_worth_m
3           Old billionaires      M               1078         6787399.62
5      Senior Wealth holders      M               1199         6114912.82
1  Established professionals      M                568         3933949.92
2           Old billionaires      F                151         1217788.48
4      Senior Wealth holders      F                193          926668.53
0  Established professionals      F                114          363054.79
7        Young entrepreneurs      M                 65          257888.89
6        Young entrepreneurs      F                 16           37886.65

In [26]:
df_1.columns

Index(['rank', 'person_name', 'gender', 'age', 'country', 'iso3',
       'wb_country_name', 'state', 'city', 'net_worth_usd_m', 'net_worth_usd',
       'source_of_wealth', 'industries', 'primary_industry', 'self_made',
       'wealth_gdp_ratio_pct', 'wealth_per_citizen_usd',
       'wealth_country_share_pct', 'sector_dominance_score', 'gdp_usd',
       'population', 'gdp_year', 'forbes_uri', 'scrape_timestamp',
       'birth_year', 'net_worth_usd_b', 'age_bracket'],
      dtype='object')

### Q5. Which Primary Industry has the highest Sector Dominance Score on Average when grouping by Country? Which Country shows a Monopoly in a single industry?

In [27]:
## Define a variable first
country_indus_stats = df_1.groupby(['primary_industry', 'country']).agg(
    avg_sector_score = ('sector_dominance_score', 'mean'),
    industry_count = ('primary_industry', 'count')).reset_index()
country_indus_stats

    primary_industry         country  avg_sector_score  industry_count
0         Automotive       Australia             16.13               1
1         Automotive         Austria             37.00               1
2         Automotive         Belgium             16.66               2
3         Automotive           China             15.26              16
4         Automotive          France             39.58               1
..               ...             ...               ...             ...
475          Telecom          Russia             17.19               3
476          Telecom          Turkey             20.03               1
477          Telecom  United Kingdom             16.65               2
478          Telecom   United States             23.35               8
479          Telecom        Zimbabwe            100.00               1

[480 rows x 4 columns]

In [28]:
## Top 10 Most Dominant Industry per Country by Sector Score
primary_indus_top10 = country_indus_stats.nlargest(10, 'avg_sector_score')
primary_indus_top10

     primary_industry               country  avg_sector_score  industry_count
39        Diversified               Albania             100.0               1
45        Diversified              Bulgaria             100.0               2
57        Diversified               Iceland             100.0               1
63        Diversified            Luxembourg             100.0               1
67        Diversified                 Nepal             100.0               1
73        Diversified              Portugal             100.0               1
81        Diversified              Tanzania             100.0               1
111  Fashion & Retail              Barbados             100.0               1
117  Fashion & Retail  Eswatini (Swaziland)             100.0               1
127  Fashion & Retail                Monaco             100.0               2

In [29]:
## Bottom 10 Least Dominant Industry per Country by Avg Sector Score
primary_indus_bottom10 = country_indus_stats.nsmallest(10, 'avg_sector_score')
primary_indus_bottom10

               primary_industry country  avg_sector_score  industry_count
469                     Telecom   India              12.2               3
7                    Automotive   India              12.2              13
25   Construction & Engineering   India              12.2               5
58                  Diversified   India              12.2              18
98                       Energy   India              12.2               8
121            Fashion & Retail   India              12.2              13
163       Finance & Investments   India              12.2              19
208             Food & Beverage   India              12.2              19
251                  Healthcare   India              12.2              41
278                   Logistics   India              12.2               1

In [70]:
df_1.columns

Index(['rank', 'person_name', 'gender', 'age', 'country', 'iso3',
       'wb_country_name', 'state', 'city', 'net_worth_usd_m', 'net_worth_usd',
       'source_of_wealth', 'industries', 'primary_industry', 'self_made',
       'wealth_gdp_ratio_pct', 'wealth_per_citizen_usd',
       'wealth_country_share_pct', 'sector_dominance_score', 'gdp_usd',
       'population', 'gdp_year', 'forbes_uri', 'scrape_timestamp',
       'birth_year', 'net_worth_usd_b', 'age_bracket'],
      dtype='object')

In [30]:
## Which countries show a Monopoly in A Single industry with 100% absolute monopoly dominance?
    ## First find Unique industries per each country
country_indus = df_1.groupby('country')['primary_industry'].nunique().reset_index()
country_indus

           country  primary_industry
0      Afghanistan                 1
1          Albania                 1
2          Algeria                 1
3        Argentina                 5
4          Armenia                 1
..             ...               ...
75  United Kingdom                15
76   United States                18
77       Venezuela                 1
78         Vietnam                 4
79        Zimbabwe                 1

[80 rows x 2 columns]

In [32]:
## Then obtain specific columns
country_indus_columns = ['country', 'primary_industry']

In [33]:
##Filter to only countries only having ONLY one  Industry
total_monopoly = country_indus[country_indus['primary_industry']==1]
total_monopoly

                 country  primary_industry
0            Afghanistan                 1
1                Albania                 1
2                Algeria                 1
4                Armenia                 1
7               Barbados                 1
9                 Belize                 1
11              Bulgaria                 1
16               Croatia                 1
21               Estonia                 1
22  Eswatini (Swaziland)                 1
25               Georgia                 1
28              Guernsey                 1
31               Iceland                 1
40         Liechtenstein                 1
41            Luxembourg                 1
44                Monaco                 1
46                 Nepal                 1
51                  Oman                 1
52              Pakistan                 1
56              Portugal                 1
70              Tanzania                 1
77             Venezuela                 1
79              Zimbabwe                 1

In [34]:
## Next we obtain Country names with Total Monopoly on an Industry
monopoly_stats = []
for country in total_monopoly['country']:
    industry = df_1[df_1['country']== country]['primary_industry'].iloc[0]
    billionaire_count = len(df_1[df_1['country'] == country])
    total_net_worth =  df_1[df_1['country'] == country]['net_worth_usd_m'].sum()

    monopoly_stats.append({
        'country': country,
        'monopoly_industry': industry,
        'billionaire_count': billionaire_count,
        'total_net_worth_usd_m': total_net_worth
    })

monopoly_df = pd.DataFrame(monopoly_stats).sort_values('total_net_worth_usd_m', ascending = False)
monopoly_df

,country,monopoly_industry,billionaire_count,total_net_worth_usd_m
9,Eswatini (Swaziland),Fashion & Retail,1,17618.62
21,Venezuela,Finance & Investments,1,11227.11
15,Monaco,Fashion & Retail,2,10307.00
10,Georgia,Finance & Investments,2,8717.87
19,Portugal,Diversified,1,7682.26
6,Bulgaria,Diversified,2,5826.90
17,Oman,Real Estate,1,3853.92
8,Estonia,Finance & Investments,2,3681.15
5,Belize,Finance & Investments,1,3676.86
2,Algeria,Food & Beverage,1,3632.10
11,Guernsey,Finance & Investments,1,3186.30
22,Zimbabwe,Telecom,1,2178.85
7,Croatia,Metals & Mining,1,2125.00
20,Tanzania,Diversified,1,2093.97
16,Nepal,Diversified,1,2077.33
1,Albania,Diversified,1,1861.09
0,Afghanistan,Real Estate,1,1399.31
18,Pakistan,Technology,1,1300.00
13,Liechtenstein,Healthcare,1,1286.53
3,Armenia,Finance & Investments,1,1252.37
14,Luxembourg,Diversified,1,1195.49
4,Barbados,Fashion & Retail,1,1028.11
12,Iceland,Diversified,1,1000.00

### Q6. Create filtered comparison for USA VS China Billionaires whose are Only Self-Made and the Primary indusry is Technology or Diversified. Which of the group has a higher wealth_gdp_ratio_pct?

In [35]:
country_comparison= df_1[
    (df_1['country'].isin(['United States','China'])) &
    (df_1['self_made']== True) &
    (df_1['primary_industry'].isin(['Technology', 'Diversified']))
    ]

# Group by country and calculate statistics

comparison_stats = country_comparison.groupby('country').agg(
    avg_wealth_gdp_ratio=('wealth_gdp_ratio_pct', 'mean'),
    median_wealth_gdp_ratio=('wealth_gdp_ratio_pct', 'median'),
    count=('wealth_gdp_ratio_pct', 'count'),
    min_ratio=('wealth_gdp_ratio_pct', 'min'),
    max_ratio=('wealth_gdp_ratio_pct', 'max')
).reset_index()

print("=== USA vs CHINA: Self-Made Billionaires in Technology/Diversified ===")
print(comparison_stats)

## Result: United States of America has a higher average wealth to gdp ratio at 0.056 as compared to China's 0.029. The United States of America also has the Most Self Made Billionaires Billionaires at 212 while China has only 100

=== USA vs CHINA: Self-Made Billionaires in Technology/Diversified ===
         country  avg_wealth_gdp_ratio  median_wealth_gdp_ratio  count  \
0          China              0.029019                 0.010308    106
1  United States              0.056161                 0.009804    211

   min_ratio  max_ratio
0   0.005378   0.369722
1   0.003415   2.784704

## PART C: STATISTICAL COMPUTATION

### Q7.What is the average wealth-to-GDP ratio for billionaires across all countries?

In [36]:
avg_wealth_to_gdp = df_1['wealth_gdp_ratio_pct'].mean()



## Lets convert it to a percentage
avearge_ratio_percentage = avg_wealth_to_gdp * 100
print("Average Wealth To GDP:", round(avg_wealth_to_gdp,2),"%")

Average Wealth To GDP: 0.81 %

### Q8. Which country has the highest number of billionaires in the dataset?

In [37]:
## First calculate networth billions i.e in USD_b 
net_worth_usd_b = df_1['net_worth_usd_m']/1000
net_worth_usd_b

## We then groupby Country and Sort in Descending Order
country_billionaires = df_1.groupby(['country']).agg(
    billionaire_count = ('person_name', 'count'),
    net_worth_b = ('net_worth_usd_b', 'sum')).reset_index()

top_countries = country_billionaires.sort_values('net_worth_b', ascending=False)
top_countries

          country  billionaire_count  net_worth_b
76  United States                978   8342.85733
14          China                528   2134.67932
32          India                225    989.62296
26        Germany                212    985.82188
59         Russia                149    653.32662
..            ...                ...          ...
40  Liechtenstein                  1      1.28653
4         Armenia                  1      1.25237
41     Luxembourg                  1      1.19549
7        Barbados                  1      1.02811
31        Iceland                  1      1.00000

[80 rows x 3 columns]

In [38]:
## Find the top 20 countries with highest Net Worth
top_20_countries = country_billionaires.nlargest(20,'net_worth_b')
top_20_countries

           country  billionaire_count  net_worth_b
76   United States                978   8342.85733
14           China                528   2134.67932
32           India                225    989.62296
26         Germany                212    985.82188
59          Russia                149    653.32662
24          France                 54    591.64015
36           Italy                 83    463.42460
12          Canada                 81    443.79717
29       Hong Kong                 70    422.58723
68     Switzerland                 43    273.62695
65           Spain                 44    270.44105
75  United Kingdom                 55    270.35057
10          Brazil                 74    265.15082
43          Mexico                 24    263.18940
69          Taiwan                 65    239.32351
5        Australia                 56    238.11662
35          Israel                 43    228.99656
67          Sweden                 53    220.15025
37           Japan                 44    218.49169
33       Indonesia                 32    170.06876

### Q9. Which gender has the higher average wealth-to-GDP ratio?

In [ ]:
gender_comparison = df_1.groupby(['gender']).agg(
    avg_wealth_to_gdp = ('wealth_gdp_ratio_pct', 'mean'))
print(gender_comparison)

    ## The Male Gender has a higher wealth to gdp ratio at 0.89 compared to the female gender at 0.32

### Q10. Is there a relationship between age and networth?

In [43]:
age_net_rship = df_1['age'].corr(df_1['net_worth_usd'])
age_net_rship

np.float64(0.03082796979028872)

### Q11. Which country has the widest variation (standard deviation) in wealth-to-GDP ratios?

In [49]:
country_wealth_variation = df_1.groupby('country')['wealth_gdp_ratio_pct'].std()
country_wealth_variation

## To View Countries with the Highest Variations
top_country_wealth_var = country_wealth_variation.idxmax()
top_country_wealth_var

'St. Kitts and Nevis'

In [50]:
top_10 = country_wealth_variation.nlargest(10)
print(top_10)

country
St. Kitts and Nevis    462.408817
Cyprus                  22.847964
Monaco                  14.662296
Georgia                  6.862029
Lebanon                  6.664037
Chile                    5.551657
Nigeria                  4.696233
Austria                  2.604497
Czech Republic           2.566424
Hong Kong                2.358803
Name: wealth_gdp_ratio_pct, dtype: float64

In [40]:
df_1.columns

Index(['rank', 'person_name', 'gender', 'age', 'country', 'iso3',
       'wb_country_name', 'state', 'city', 'net_worth_usd_m', 'net_worth_usd',
       'source_of_wealth', 'industries', 'primary_industry', 'self_made',
       'wealth_gdp_ratio_pct', 'wealth_per_citizen_usd',
       'wealth_country_share_pct', 'sector_dominance_score', 'gdp_usd',
       'population', 'gdp_year', 'forbes_uri', 'scrape_timestamp',
       'birth_year', 'net_worth_usd_b', 'age_bracket'],
      dtype='object')